name: .NET Deploy

on:
  push:
    branches: [ main ]
    paths: Application/**
  pull_request:
    branches: [ main ]
    paths: Application/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  registryName: 'a7ltm5uwsxhxempnpreg.azurecr.io'
  appPrefix: 'a7ltm5uwsxhxe'
  repositoryName : 'techboost/dotnetcoreapp'
  dockerFolderPath: 'Application/src/RazorPagesTestSample'
  tag: ${{github.run_number}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
   
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Build
      run: dotnet build --no-restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  dockerBuildPush:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      run: docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        
    - name: Docker Build
      run: docker build -t ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }} --build-arg build_version=${{ env.tag }} ${{ env.dockerFolderPath }}
        
    - name: Docker Push
      run: docker push ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: dockerBuildPush
    environment:
      name: dev
      url: https://${{ env.appPrefix }}-dev.azurewebsites.net/
        
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.appPrefix }}-dev'
          images: ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

  deploy-to-test:
    runs-on: ubuntu-latest
    needs: [dockerBuildPush, deploy-to-dev]
    environment:
      name: test
      url: https://${{ env.appPrefix }}-test.azurewebsites.net/
            
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true

      - uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.appPrefix }}-test'
          images: ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: [dockerBuildPush, deploy-to-test]
    environment:
      name: prod
      url: https://${{ env.appPrefix }}-prod.azurewebsites.net/
            
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true

      - uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.appPrefix }}-prod'
          images: ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}